apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-restart-alerts
  namespace: default
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodRestartingFrequently
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently"
        description: "A pod has restarted more than 2 times in the last 5 minutes."
